version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    environment:
      TZ: Asia/Tokyo
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
  mongo:
    image: mongo:4.2.5-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_APP_USERNAME: $MONGO_APP_USERNAME
      MONGO_APP_PASSWORD: $MONGO_APP_PASSWORD
      TZ: Asia/Tokyo
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
      - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/
    command: mongod
